### ISSUE TITLE
Is the child-theme still supported?

### ISSUE THREAD

**Issue by JusticeRage** [Codeinwp/neve-child#3]
Hi! I just wanted to check whether the child theme is still supported?
I tried importing it following [these instructions](https://docs.themeisle.com/article/985-how-to-create-a-child-theme-for-neve) to make some modifications, but it completely broke the layout of the website. I expected it to initially look exactly like the original Neve before I made any modifications to it.

I know I'm not providing enough information to trace back the issue. I'm a Wordpress beginner and don't want to take too much of your time - the only thing I want is to verify that this project is still working as intended before I dig further into the code.

Thanks in advance!

**Comment by vytisbulkevicius** [comment]
Hi @JusticeRage,

When changing themes settings are made in Customizer are not automatically transferred so if you made changes in the Neve theme (Customizer) and then switched to the child theme, it's expected that changes are lost.

You can use this plugin https://wordpress.org/plugins/customizer-export-import/ and **export** Customizer settings when Neve parent theme is active, then switch to the child theme and **import** the same file exported from the parent theme.

This way you should have all your settings in the child theme as they were in the parent.

I hope it helps!
